### ISSUE TITLE
No directory 'get_baseline_production' in src/

### ISSUE THREAD

**Issue by dannytoomey** [wwiecek/covid-vaccine-timeline#15]
Hi Witold,

I'm following the vignette that walks through running the simulations and it references a directory named `get_baseline_production` that I don't see in the `src` directory. Was this directory removed or renamed?

Best regards,

Danny Toomey

**Comment by davidoj** [comment]
I've updated the vignette so that it is consistent with the current pipeline (`get_baseline_production` is no longer used).
