### ISSUE TITLE
Dependency files not an artefact of generate_counterfactuals

### ISSUE THREAD

**Issue by dannytoomey** [wwiecek/covid-vaccine-timeline#22]
@davidoj @TDulka --

I pulled the most recent changes and now I get an odd error. When I try to generate the preprint, I get 
```
Error: Dependency files not an artefact of generate_counterfactuals/20230530-223122-e679e76f:
- 'model_fits/reported_deaths/GBR.Rds'
- 'model_fits/reported_deaths/USA.Rds’
```
The latest version of `generate_counterfactuals` on my machine is `20230530-223122-e679e76f`, with a structure of:
```
- 20230530-223122-e679e76f/
    | - model_fits/
        | - reported_deaths/
            | - GBR.rds
            | - USA.rds
```
so I'm not sure why orderly would think these files are missing. I'm re-running generate_counterfactuals right now to see if that fixes things, but I have a feeling this has something to do with orderly's dependency management, which I don't really understand. 

update - finished running generate_counterfactuals and the error persists

**Comment by davidoj** [comment]
As these files are now used to generate one of the plots, they need to be added to `generate_counterfactuals/orderly.yml`. I'm making this change in my next commit (I'm also correcting some dates)

**Comment by dannytoomey** [comment]
Excellent, thanks David!

**Comment by davidoj** [comment]
I've pushed a commit adjusting dependencies, you shouldn't need to rerun generate counterfactuals (sorry for the delay, looking after kids + testing changes)
